### ISSUE TITLE
"List" command should return all the panels to it's original state

### ISSUE THREAD

**Issue by cjinting-nus** [CS2113-AY1819S1-W13-1/main#107]
As of now, the list command does not do anything when invoked.

The idea of list command should be to allow the original list to be shown to the user.
Should it still be called list? Or is there a more appropriate name for this command.

**Comment by bennchong** [comment]
It depends on the other functions such as find or group. If these functions act on only 'friends' panel, then list should list all friend again. 

But if these functions also work on 'Others' panel, then I believe list should be for both panels. 

One suggestion is perhaps we change the name to `listall`, and then have a compulsory parameter that requires 'friends' or 'others' to select which panel.
