### ISSUE TITLE
Final command list for v1.4

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#142]
Inherited/small modifications from AB4:
`help` - show help screen
`edit` - edit your own details
`find` - find by name
`listall` - return back after `find` or `group`
`history` - shows history
`undo` - undo last action
`redo` - redo last action

Security (Ben)
`login` - logs in
`logout` - logs out
`register` registers new user
`ui` - shows user interface

Timing (NF)
`select` - selecing friend to view timetable
`add` - add time slot
`delete` - delete time slot
`free` - deconflict timetables
`clear` - clear your timetable

Social (Jasper)
`friend` - add friend
`unfriend` remove friend
`group` - search by group (formally `tag`)

Import/export (Alexis)
`import` - imports timetable
`export` - exports timetable

Commands that work with `undo` and `redo`:
`edit`, `add`, `delete`, `clear`, `friend`, `unfriend`, `import`

Commands that work on the login screen:
`login`, `register`, `ui`, `help`, `exit`

Commands that work on the main app:
Everything except `login`, `register`, `ui`

**Comment by nianfei97** [comment]
Question: do we want to keep the aliases? It's getting annoying to maintain them, not to mention that we don't have enough letters, with the amount of commands we have.

**Comment by nianfei97** [comment]
Closing #119, #123, #131, since those deal with the command word/aliases issue

**Comment by alexiscatnip** [comment]
Maybe we could keep aliases for the most-used commands?

**Comment by cjinting-nus** [comment]
I've updated the `list` command to be `listall`, I think it reflects the actual function of the command better. The alias `l` can still be used so I don't see any inconvenience caused.

**Comment by bennchong** [comment]
> Question: do we want to keep the aliases? It's getting annoying to maintain them, not to mention that we don't have enough letters, with the amount of commands we have.

Am i right to say that not every command has to have aliases? If not then I see no reason to get rid of it due to the reason of not having enough letters

**Comment by nianfei97** [comment]
Final command list with aliases, in order

Section 3: Register and log in
`register` registers new user (no alias)
`login` - logs in (no alias)
`ui` - shows user interface (no alias)

Section 4: Standard features
`help` - show help screen ('h')
`edit` - edit your own details (no alias)
`find` - find by name (`f`)
`group` - search by group (`g`)
`listall` - return back after `find` or `group` (`l`)
`friend` - add friend (`af`)
`unfriend` remove friend (`uf`)
`select` - selecing friend to view timetable (`s`)
`add` - add time slot (`a`)
`delete` - delete time slot (`d`)
`clear` - clear your timetable (`c`)
`free` - deconflict timetables (no alias)
`import` - imports timetable (`i`)
`export` - exports timetable (`e`)
`undo` - undo last action (`u`)
`redo` - redo last action (`r`)
`history` - shows history (no alias)
`logout` - logs out (no alias)
`exit` - exits the app (`x`)

Commands that work with `undo` and `redo`:
`edit`, `add`, `delete`, `clear`, `import`

**Comment by bennchong** [comment]
Final command list with aliases, in order (UPDATED)

Section 3: Register and log in
`register` registers new user ('re')
`login` - logs in ('li')
`ui` - shows user interface ('ui')

Section 4: Standard features
`help` - show help screen ('h')
`edit` - edit your own details ('ed')
`find` - find by name (`f`)
`group` - search by group (`g`)
`listall` - return back after `find` or `group` (`l`)
`friend` - add friend (`af`)
`unfriend` remove friend (`uf`)
`select` - selecing friend to view timetable (`s`)
`add` - add time slot (`a`)
`delete` - delete time slot (`d`)
`clear` - clear your timetable (`c`)
`free` - deconflict timetables ('fr')
`import` - imports timetable (`i`)
`export` - exports timetable (`e`)
`undo` - undo last action (`u`)
`redo` - redo last action (`r`)
`history` - shows history (h)
`logout` - logs out (lo)
`exit` - exits the app (`x`)

Commands that work with `undo` and `redo`:
`edit`, `add`, `delete`, `clear`, `import`

**Comment by bennchong** [comment]
True but aliases are for season users. So by having them, you are just giving them the option to use it. If they don't remember, just use the full length one

**Comment by cjinting-nus** [comment]
Alright, that's true as well
