### ISSUE TITLE
Improve colour randomisation for timetable

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#144]
Currently, the colour for each timeslot is just generated at random without considering the number of timeslots with the same colour already in the timetable.

It is possible to make it such that duplicates are minimised.

**Comment by alexiscatnip** [comment]
I suppose you could remove the 'color' in each `TimeSlot`, and instead assign a color on-the-fly in your `addTimeSlot` method.

Then you can ensure that `TimeSlots` in-sequence have different colors.

**Comment by nianfei97** [comment]
Problem with that is every time the timetable refreshes (when you add/remove a timeslot, or even resize the window), the colours of all timeslots change.

It leads to a really interesting psychedelic effect when you resize the window.

Probably will only look into it after mid v1.4, if I even bother

**Comment by bennchong** [comment]
One suggestion is to cycle through the colors? That way itll be consistent
