### ISSUE TITLE
Compulsory Information when registering

### ISSUE THREAD

**Issue by bennchong** [CS2113-AY1819S1-W13-1/main#150]
Guys I need some input, do we want all fields such as phone, email and address to be compulsory? My take is that it is non-essential due to the purpose of our application, and hence its extra information that need not be compulsory when signing up. Do let me know what you all think

**Comment by alexiscatnip** [comment]
Agree also. I suppose since its registeration, then the only necessary items are the username and password

**Comment by cjinting-nus** [comment]
Technically it is not required, but it involves modifying the original function of the filteredList and also all the tests that come with it :>

**Comment by bennchong** [comment]
> Technically it is not required, but it involves modifying the original function of the filteredList and also all the tests that come with it :>

The filtered list requires the fields to be present?

**Comment by cjinting-nus** [comment]
From what I understand, running the original `add` command requires all the fields, with the exception of tags, to be nonnull. They would not allow for other fields to be left empty.

**Comment by cjinting-nus** [comment]
But I think internally filteredList does not check for the fields to be non-null, I think?

**Comment by bennchong** [comment]
> From what I understand, running the original `add` command requires all the fields, with the exception of tags, to be nonnull. They would not allow for other fields to be left empty.

On my local repo I've changed this to accommodate empty fields (not so trivial), all left is the tests since addCommand is basically changed to registerCommand.

**Comment by cjinting-nus** [comment]
> 
> 
> > From what I understand, running the original `add` command requires all the fields, with the exception of tags, to be nonnull. They would not allow for other fields to be left empty.
> 
> On my local repo I've changed this to accommodate empty fields (not so trivial), all left is the tests since addCommand is basically changed to registerCommand.

Sounds good, nice one Ben

**Comment by bennchong** [comment]
> > > From what I understand, running the original `add` command requires all the fields, with the exception of tags, to be nonnull. They would not allow for other fields to be left empty.
> > 
> > 
> > On my local repo I've changed this to accommodate empty fields (not so trivial), all left is the tests since addCommand is basically changed to registerCommand.
> 
> Sounds good, nice one Ben

Thanks. Closing this 👍
