### ISSUE TITLE
Size of PersonCard in Others panel & Empty space in Me panel

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#160]
Currently, there is empty space in the Others panel (due to hidden information) and empty space in the Me panel (due to there being only 1 PersonCard in it).

**Comment by cjinting-nus** [comment]
Do you think this is better?

![image](https://user-images.githubusercontent.com/37281349/48130148-a554cc00-e2c6-11e8-9622-a73cf32ceb3e.png)

**Comment by nianfei97** [comment]
Looks good to me

**Comment by cjinting-nus** [comment]
I'll fix this together with the other panels and push it together as 1 pr for v1.4 (final hopefully)

**Comment by bennchong** [comment]
> Do you think this is better?
> 
> ![image](https://user-images.githubusercontent.com/37281349/48130148-a554cc00-e2c6-11e8-9622-a73cf32ceb3e.png)

Sick la Pual, proud of you. it legit looks good
