### ISSUE TITLE
Login screen glitches when window is at minimum size

### ISSUE THREAD

**Issue by cjinting-nus** [CS2113-AY1819S1-W13-1/main#164]
I think #153 will fix this but I'll just put it up nontheless

![image](https://user-images.githubusercontent.com/37281349/48251475-ba536b80-e43c-11e8-9ca1-2e0e077de6ab.png)

**Comment by nianfei97** [comment]
Is it still broken? I thought the minimum app size of 1280x720 fixed it

**Comment by bennchong** [comment]
Maybe it must be bigger than that?

**Comment by bennchong** [comment]
Leave this to me. I think it has to do with the SecurityBoxDisplay so ps ill take this

**Comment by bennchong** [comment]
Fixed it in the latest PR
