### ISSUE TITLE
Edit command causes issues with login

### ISSUE THREAD

**Issue by cjinting-nus** [CS2113-AY1819S1-W13-1/main#171]
Modifying the name (also means changing the username in this case) would cause the login to stop working

I think this is due to the method `logic.matchUserToPerson()`

Proposed solution would be to either:
1. Modify such that changing the name modifies the username as well (in users.json)
2. Disallow the modification of the username/name

![image](https://user-images.githubusercontent.com/37281349/48298374-648fc980-e4f7-11e8-874e-f802dce2118a.png)

**Comment by nianfei97** [comment]
2 is probably the easiest way, especially at this juncture

**Comment by cjinting-nus** [comment]
I think it will affect how friends work as well since they are stored on Person after calling `friend` or `unfriend`

**Comment by bennchong** [comment]
> I think it will affect how friends work as well since they are stored on Person after calling `friend` or `unfriend`

Yep it will. I will go with 2 as its pretty common that you can't change your username
