### ISSUE TITLE
Export command exporting currently-displayed timetable, not user's timetable

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#187]
![image](https://user-images.githubusercontent.com/35740636/48315471-95642180-e611-11e8-94f2-8585f3060141.png)

@alexiscatnip 
Can I confirm whether this is intended behaviour? Because it seems strange for the timetable exported to be the currently-displayed timetable. Shouldn't it be the user's own timetable instead?

Should probably read `TimeTable timeTable = model.getUser().getTimeTable();` instead if it's the latter

**Comment by alexiscatnip** [comment]
Yes, intended behavior. Intended behavior is for the currently-shown timetable to be exported.
