### ISSUE TITLE
Config.json newline at EOF 

### ISSUE THREAD

**Issue by bennchong** [CS2113-AY1819S1-W13-1/main#33]
Every time the project is built, it will automatically remove the extra line at EOF in config.json. This creates a problem with Travis, and will fail is test due to this missing line.

**Comment by nianfei97** [comment]
Huh, weird. Maybe that's why it's not originally tracked in git.

I guess everyone has the latest version of `config,json` already so it should be able to put the file back into `.gitignore`?
