### ISSUE TITLE
Concept of "me"

### ISSUE THREAD

**Issue by nianfei97** [CS2113-AY1819S1-W13-1/main#38]
Since for our app, you're only going to be able to edit your own timetable and details, I think it is important to have a concrete idea of how we are going to implement the concept of "me" in the backend.

@cjinting-nus How do you plan to implement this?

**Comment by cjinting-nus** [comment]
I am still in the midst of discussion with @bennchong , but most likely it will be something along these lines...
User keys in id + password to log-in, user will be tied to one of the `Person` in the book, the list of friends tied to the `Person` will be loaded and managed from there

**Comment by nianfei97** [comment]
Hmm then "I" won't appear in either user pane, right?

That's going to be a little problematic since the current implementation of `edit` (and my upcoming implementation of `addtime` and `removetime` relies on the person to be edited having an `Index` that's visible, so either that implementation probably needs to be reworked somewhere down the line...

Is there going to be a "me" pane?

**Comment by bennchong** [comment]
> Hmm then "I" won't appear in either user pane, right?
> 
> That's going to be a little problematic since the current implementation of `edit` (and my upcoming implementation of `addtime` and `removetime` relies on the person to be edited having an `Index` that's visible, so either that implementation probably needs to be reworked somewhere down the line...
> 
> Is there going to be a "me" pane?

As just discussed, we will be going to have a separate "me" panel, called "Profile". It is going to be a PersonListPanel, albeit just showing yourself. 

To address how the program know which user is login at the moment, under the SecurityManager there will be a class called User, which composes of a Person Class, which is the user that logged in. This User Class would have methods such as isFriend(), addFriend(), so as to allow the panel to show friends. 

@nianfei97 @cjinting-nus @alexiscatnip

**Comment by cjinting-nus** [comment]
I think we had a great summary from Ben and as per our discussion earlier today, we will move forward with our current plan. I'll mark this issue as completed.
