### ISSUE TITLE
v1.3 Road Map (Jasper)

### ISSUE THREAD

**Issue by cjinting-nus** [CS2113-AY1819S1-W13-1/main#42]
Features
- [x] Have additional pane to show self (current user) - integration with Timetable v1.2

Tests
- [ ] TagCommand Tests
- [x] FriendCommand Tests
- [ ] UnfriendCommand Tests

**Comment by nianfei97** [comment]
Closed.

Please update/migrate remaining tasks to v1.4, thanks.
